# docker-compose.yaml
# docker-compose up -d
# docker-compose stop
version: '3'

services:
  db-service:
    image: vdigital/mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=g0th@m
      - MYSQL_DATABASE=OPENHEALTH

  frontend:
    image: vdigital/phpmicro:dev
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db-service
      - DB_NAME=OPENHEALTH
      - DB_USER=
      - DB_PASS=
    ports:
      - 80:80
    depends_on:
      - db-service
